version: '3.2'
services:
  web:
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
      dockerfile: ./docker/Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - database
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-remote_host=172.18.19.1}
      PHP_XDEBUG_ENABLED: ${XDEBUG_ENABLED:-false}
      PHP_IDE_CONFIG: "serverName=Backend"
    volumes:
      - ./:/var/www/html
    container_name: housing_unit_web
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: housing_unit
    volumes:
      - housing_unit_database:/var/lib/mysql
    ports:
      - "3343:3306"
    container_name: housing_unit_db
volumes:
  housing_unit_database: null
